### ISSUE TITLE
Unhandeled connection reset events when Blynk looses connection to server

### ISSUE THREAD

**Issue by dcsim0n** [dcsim0n/JAGROMissionControl#2]
```events.js:312
    throw err; // Unhandled 'error' event
    ^

Error [ERR_UNHANDLED_ERROR]: Unhandled error. ('ECONNRESET')
    at Blynk.emit (events.js:310:17)
    at Blynk.error (/home/pi/Development/JAGROMissionControl/node_modules/blynk-library/blynk.js:649:8)
    at exports.TcpClient.<anonymous> (/home/pi/Development/JAGROMissionControl/node_modules/blynk-library/blynk.js:612:4
8)
    at exports.TcpClient.emit (events.js:321:20)
    at Socket.<anonymous> (/home/pi/Development/JAGROMissionControl/node_modules/blynk-library/blynk-node.js:59:14)
    at Socket.emit (events.js:321:20)
    at emitErrorNT (internal/streams/destroy.js:84:8)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  code: 'ERR_UNHANDLED_ERROR',
  context: 'ECONNRESET'
}
```
If connection is lost, Blynk will throw "ECONNRESET" event in the main application loop, causing all other event handling to stop.

**Comment by dcsim0n** [comment]
Resolved in: e2ca4f0
